import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Link from "next/link";

const Home: NextPage = () => {
  let a = [
    { a: 1, b: 2 },
    { a: 10, b: 30 }
  ];
  let b = { a: 1, b: 186 };
  let c = { ...a, b };
  console.log(c, "c");

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h3>
          Start working with file <code>src/index.tsx</code>
        </h3>
        <div>
          <Link href="/contact">To Contacts</Link>
        </div>
      </main>
    </div>
  );
};

export default Home;
